version: 1.0.{build}

skip_tags: true

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  COVERALLS_REPO_TOKEN:
    secure: oxB2l7vHmBZHBJbl8pFZIGUao5m426LkQInK8WFv235cjMPLzPR+Wz3mdbYTSawM

before_build:
 - nuget restore ".\Tree\Tree.NUnit.sln"
 - nuget install OpenCover -Version 4.6.519 -OutputDirectory Tree\packages
 - nuget install coveralls.net -Version 0.6.0 -OutputDirectory Tree\packages

build:
  project: .\Tree\Tree.NUnit.sln
  verbosity: detailed

test_script:
- ps: >-
    .\Tree\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe "-targetargs:""Tree\Tree.NUnit\bin\Release\Tree.NUnit.dll" -output:opencoverCoverage.xml
    $coveralls = (Resolve-Path "Tree/packages/coveralls.net.0.6.0/tools/csmacnz.Coveralls.exe").ToString()

    $env:APPVEYOR_BUILD_NUMBER

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
