version: 1.0.{build}

configuration: Release

platform: Any CPU

environment:
  COVERALLS_REPO_TOKEN:  
    secure: oxB2l7vHmBZHBJbl8pFZIGUao5m426LkQInK8WFv235cjMPLzPR+Wz3mdbYTSawM
  
before_build:
  - nuget restore ".\Tree\Tree.NUnit.sln"
  
build:
  project: Tree/Tree.NUnit.sln
  verbosity: detailed
  
after_test: 
# generate report for NUnit 3 testing framework:
 - cmd: Tree\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"Tree\packages\NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe" -targetargs:"/domain:single Tree\Tree.NUnit\bin\Release\Tree.NUnit.dll" -output:coverage.xml
